Add support for python 3.7 and upgrade spark to 3.0.1
hyperopt/hyperopt pull request #749
Opened 2020-09-26 00:18 UTC by panchalhp-db

- Upgrade build use to Ubuntu 18.04
- Add support for python 3.7
- Upgrade to spark 3.0.1

2020-09-26 00:35 UTC, mengxr requested changes

2020-09-26 00:35 UTC, mengxr commented on .travis.yml
> +    - SPARK_VERSION=3.0.1
With official Spark 3.0.x release, we don't need to manually download the Spark distribution jar. We just need to define the Spark version like numpy. We can also clean up download_spark_dependencies.sh.

2020-09-29 23:40 UTC, lu-wang-dl approved these changes

2020-10-07 00:39 UTC, panchalhp-db commented
@maxpumperla Could you help take a look at this PR? Thanks!

2020-10-07 08:20 UTC, merged

2020-10-07 08:20 UTC, maxpumperla commented
thanks for the update, great simplification.